name: CI
# Workflow CI

on:
  push:
    branches:
      - main
# Launch workflow -> commits on main

jobs:
  build:
    runs-on: ubuntu-latest
    # Use an virtual ubuntu to run it

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # Get the source code

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        # Use JDK 11
 
    - name: Set up jar
      run: |
        cd TourGuide
        mvn install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

    - name: Build with Maven
      run: mvn -B clean package --file TourGuide/pom.xml
      # Compiler et construire le projet avec Maven

    - name: Run tests
      run: |
        cd TourGuide
        mvn test
      # Exécuter les tests unitaires du projet


    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: TourGuide/target/*.jar
        # Télécharger les artefacts générés en tant qu'artefact de construction